// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Image6 = NULL;
lv_obj_t * ui_Spinner2 = NULL;
lv_obj_t * ui_dashboardTitle = NULL;
lv_obj_t * ui_time = NULL;
lv_obj_t * ui_todonumberTitle = NULL;
lv_obj_t * ui_todonumber = NULL;
// event funtions
void ui_event_Screen1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen2_screen_init);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image6 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image6, &ui_img_bg01_png);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 240
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 240
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Spinner2 = lv_spinner_create(ui_Screen1, 1000, 90);
    lv_obj_set_width(ui_Spinner2, 187);
    lv_obj_set_height(ui_Spinner2, 188);
    lv_obj_set_x(ui_Spinner2, -1);
    lv_obj_set_y(ui_Spinner2, 3);
    lv_obj_set_align(ui_Spinner2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Spinner2, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_dashboardTitle = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_dashboardTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dashboardTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dashboardTitle, -84);
    lv_obj_set_y(ui_dashboardTitle, -104);
    lv_obj_set_align(ui_dashboardTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dashboardTitle, "仪表盘");
    lv_obj_set_style_text_color(ui_dashboardTitle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_dashboardTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dashboardTitle, &ui_font_YBPfont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_time = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_time, 53);
    lv_obj_set_y(ui_time, -105);
    lv_obj_set_align(ui_time, LV_ALIGN_CENTER);
    lv_label_set_text(ui_time, "00月00日00:00");
    lv_obj_set_style_text_color(ui_time, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_time, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_time, &ui_font_FontCN16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_todonumberTitle = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_todonumberTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_todonumberTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_todonumberTitle, -2);
    lv_obj_set_y(ui_todonumberTitle, -51);
    lv_obj_set_align(ui_todonumberTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_todonumberTitle, "待办数量");
    lv_obj_set_style_text_color(ui_todonumberTitle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_todonumberTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_todonumberTitle, &ui_font_FontCN16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_todonumber = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_todonumber, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_todonumber, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_todonumber, -2);
    lv_obj_set_y(ui_todonumber, 11);
    lv_obj_set_align(ui_todonumber, LV_ALIGN_CENTER);
    lv_label_set_text(ui_todonumber, "0");
    lv_obj_set_style_text_color(ui_todonumber, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_todonumber, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_todonumber, &ui_font_bigNUM, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Screen1, ui_event_Screen1, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Image6 = NULL;
    ui_Spinner2 = NULL;
    ui_dashboardTitle = NULL;
    ui_time = NULL;
    ui_todonumberTitle = NULL;
    ui_todonumber = NULL;

}
