// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen2
extern void ui_Screen2_screen_init(void);
extern void ui_Screen2_screen_destroy(void);
extern void ui_event_Screen2(lv_event_t * e);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_recentTaskTitle;
extern lv_obj_t * ui_task1info;
extern lv_obj_t * ui_task1ddl;
extern lv_obj_t * ui_TabView1;
extern lv_obj_t * ui_task2info;
extern lv_obj_t * ui_task2ddl;
extern lv_obj_t * ui_TabView3;
extern lv_obj_t * ui_task3info;
extern lv_obj_t * ui_task3ddl;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

