// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_Image8 = NULL;
lv_obj_t * ui_recentTaskTitle = NULL;
lv_obj_t * ui_task1info = NULL;
lv_obj_t * ui_task1ddl = NULL;
lv_obj_t * ui_TabView1 = NULL;
lv_obj_t * ui_task2info = NULL;
lv_obj_t * ui_task2ddl = NULL;
lv_obj_t * ui_TabView3 = NULL;
lv_obj_t * ui_task3info = NULL;
lv_obj_t * ui_task3ddl = NULL;
// event funtions
void ui_event_Screen2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
    }
}

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image8 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_Image8, &ui_img_bg02_png);
    lv_obj_set_width(ui_Image8, LV_SIZE_CONTENT);   /// 240
    lv_obj_set_height(ui_Image8, LV_SIZE_CONTENT);    /// 240
    lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_recentTaskTitle = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_recentTaskTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_recentTaskTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_recentTaskTitle, -73);
    lv_obj_set_y(ui_recentTaskTitle, -104);
    lv_obj_set_align(ui_recentTaskTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_recentTaskTitle, "最近任务");
    lv_obj_set_style_text_color(ui_recentTaskTitle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_recentTaskTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_recentTaskTitle, &ui_font_YBPfont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_task1info = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_task1info, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_task1info, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_task1info, 1);
    lv_obj_set_y(ui_task1info, -67);
    lv_obj_set_align(ui_task1info, LV_ALIGN_CENTER);
    lv_label_set_text(ui_task1info, "任务信息任务信息任务信息");
    lv_obj_set_style_text_color(ui_task1info, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_task1info, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_task1info, &ui_font_FontCN16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_task1ddl = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_task1ddl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_task1ddl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_task1ddl, 1);
    lv_obj_set_y(ui_task1ddl, -46);
    lv_obj_set_align(ui_task1ddl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_task1ddl, "截止时间:00月00日00:00");
    lv_obj_set_style_text_color(ui_task1ddl, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_task1ddl, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_task1ddl, &ui_font_FontCN16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabView1 = lv_tabview_create(ui_Screen2, LV_DIR_TOP, 50);
    lv_obj_set_width(ui_TabView1, 204);
    lv_obj_set_height(ui_TabView1, 1);
    lv_obj_set_x(ui_TabView1, 0);
    lv_obj_set_y(ui_TabView1, -30);
    lv_obj_set_align(ui_TabView1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TabView1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_task2info = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_task2info, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_task2info, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_task2info, 1);
    lv_obj_set_y(ui_task2info, -9);
    lv_obj_set_align(ui_task2info, LV_ALIGN_CENTER);
    lv_label_set_text(ui_task2info, "任务信息任务信息任务信息");
    lv_obj_set_style_text_color(ui_task2info, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_task2info, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_task2info, &ui_font_FontCN16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_task2ddl = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_task2ddl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_task2ddl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_task2ddl, 1);
    lv_obj_set_y(ui_task2ddl, 12);
    lv_obj_set_align(ui_task2ddl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_task2ddl, "截止时间:00月00日00:00");
    lv_obj_set_style_text_color(ui_task2ddl, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_task2ddl, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_task2ddl, &ui_font_FontCN16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabView3 = lv_tabview_create(ui_Screen2, LV_DIR_TOP, 50);
    lv_obj_set_width(ui_TabView3, 204);
    lv_obj_set_height(ui_TabView3, 1);
    lv_obj_set_x(ui_TabView3, 0);
    lv_obj_set_y(ui_TabView3, 30);
    lv_obj_set_align(ui_TabView3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TabView3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_task3info = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_task3info, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_task3info, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_task3info, 1);
    lv_obj_set_y(ui_task3info, 50);
    lv_obj_set_align(ui_task3info, LV_ALIGN_CENTER);
    lv_label_set_text(ui_task3info, "任务信息任务信息任务信息");
    lv_obj_set_style_text_color(ui_task3info, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_task3info, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_task3info, &ui_font_FontCN16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_task3ddl = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_task3ddl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_task3ddl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_task3ddl, 1);
    lv_obj_set_y(ui_task3ddl, 71);
    lv_obj_set_align(ui_task3ddl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_task3ddl, "截止时间:00月00日00:00");
    lv_obj_set_style_text_color(ui_task3ddl, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_task3ddl, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_task3ddl, &ui_font_FontCN16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Screen2, ui_event_Screen2, LV_EVENT_ALL, NULL);

}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    ui_Image8 = NULL;
    ui_recentTaskTitle = NULL;
    ui_task1info = NULL;
    ui_task1ddl = NULL;
    ui_TabView1 = NULL;
    ui_task2info = NULL;
    ui_task2ddl = NULL;
    ui_TabView3 = NULL;
    ui_task3info = NULL;
    ui_task3ddl = NULL;

}
